#!/bin/bash

pgrep -f /home/youssef/.config/dwm-conf/dwmscript.sh > /home/youssef/.config/dwm-conf/dumpfile

while read -r pid;
do
    kill $pid 2>/dev/null
done < /home/youssef/.config/dwm-conf/dumpfile

/home/youssef/.config/dwm-conf/dwmscript.sh &